<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SymptomsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('symptoms')->insert([
            [
                'name' => 'Bawah daun berwarna keperakan',
                'description' => 'Bagian bawah daun tanaman cabai mengalami perubahan warna menjadi keperakan atau mengkilap, berbeda dengan warna hijau normal yang biasanya ada pada daun sehat. Permukaan bawah daun yang terkena tampak lebih licin atau mengkilap, dan kadang-kadang dapat ditemukan bintik-bintik kecil atau bercak keputihan. Selain perubahan warna, daun yang terinfeksi mungkin juga menunjukkan gejala lain seperti menggulung, menguning, atau bahkan mengering jika kerusakan berlanjut. Gejala ini seringkali dimulai dari bagian bawah daun dan bisa menyebar ke seluruh daun jika tidak ditangani. Pada tahap awal infeksi, seringkali bagian atas daun tetap terlihat normal atau kurang terpengaruh.'
            ],
            [
                'name' => 'Bawah daun berwarna tembaga',
                'description' => 'Bagian bawah daun tanaman cabai mengalami perubahan warna menjadi tembaga, yang berbeda dengan warna hijau normal yang seharusnya ada pada daun sehat. Permukaan bawah daun yang terkena tampak lebih kaku dan mungkin mengkilap, dengan warna tembaga yang menyebar tidak merata. Kadang-kadang, bintik-bintik kecil atau bercak coklat dapat ditemukan di daerah yang terkena. Selain perubahan warna, daun yang terinfeksi mungkin menunjukkan gejala lain seperti mengering, menguning, atau menggulung. Seiring berjalannya waktu, daun dapat mengalami kerusakan lebih parah, termasuk nekrosis atau kematian jaringan. Gejala ini seringkali dimulai dari bagian bawah daun dan dapat menyebar ke seluruh daun atau ke daun-daun lain di sekitar jika tidak segera ditangani. Pada tahap awal infeksi, bagian atas daun mungkin tetap terlihat normal.'  
            ],
            [
                'name' => 'Daun berkerut',
                'description' => 'Daun tanaman cabai yang terkena tampak berkerut atau kusut, dengan permukaan yang tidak rata. Daun mungkin terlihat menggulung atau melipat, baik pada tepi maupun seluruh permukaan daun. Daun yang berkerut sering kali terasa lebih kasar dan kaku dibandingkan dengan daun sehat yang normalnya halus dan lentur. Selain itu, daun yang mengalami kerutan mungkin juga lebih kecil dari ukuran normal karena pertumbuhannya terganggu. Selain berkerut, daun mungkin menunjukkan perubahan warna, seperti menguning, munculnya bercak-bercak, atau warna yang lebih pucat dibandingkan dengan daun sehat. Tanaman cabai yang daunnya berkerut seringkali mengalami pertumbuhan yang terhambat secara keseluruhan. Pertumbuhan tunas dan buah mungkin juga terganggu, yang dapat mempengaruhi hasil panen.'  
            ],
            [
                'name' => 'Daun keriting',
                'description' => 'Daun tanaman cabai yang terkena gejala ini tampak keriting, dengan tepi daun yang melengkung ke atas atau ke bawah. Seluruh permukaan daun bisa tampak tidak beraturan dan melipat-lipat. Daun yang keriting biasanya terasa lebih kasar dan kaku dibandingkan dengan daun yang sehat, yang normalnya halus dan lentur. Daun yang terkena keriting seringkali lebih kecil dari ukuran normal karena pertumbuhannya terhambat. Selain keriting, daun mungkin menunjukkan perubahan warna seperti menguning, munculnya bercak-bercak, atau warna yang lebih pucat dibandingkan dengan daun sehat. Tanaman cabai dengan daun yang keriting sering mengalami pertumbuhan yang terhambat secara keseluruhan. Pertumbuhan tunas dan buah bisa terganggu, yang berpotensi mengurangi hasil panen.'  
            ],
            [
                'name' => 'Daun kekuningan',
                'description' => 'Gejala pada tanaman cabai ini adalah ketika daun-daun tanaman cabai mulai mengalami perubahan warna menjadi kuning. Warna kuning ini bisa muncul secara merata di seluruh daun atau terbatas pada bagian-bagian tertentu. Perubahan warna ini biasanya merupakan tanda adanya masalah dalam kesehatan tanaman, seperti defisiensi nutrisi, gangguan dalam penyerapan nutrisi, penyakit, atau serangan hama. Daun yang kekuningan seringkali terlihat kusam dan kurang sehat. Selain perubahan warna, daun yang terkena gejala ini mungkin juga menunjukkan gejala lain seperti menggulung, mengering, atau mengkerut. Penting untuk melakukan identifikasi penyebabnya dan mengambil tindakan yang sesuai, seperti memberikan pupuk yang tepat, mengontrol serangan hama atau penyakit, atau memperbaiki kondisi lingkungan tanaman, untuk mengembalikan kesehatan daun dan pertumbuhan tanaman secara keseluruhan.'  
            ],
            [
                'name' => 'Daun terpuntir',
                'description' => 'Gejala pada tanaman cabai ini adalah ketika daun-daun tanaman tersebut tampak melengkung atau berputar, dengan tepi daun yang memutar ke berbagai arah. Permukaan daun secara keseluruhan dapat terlihat tidak beraturan dan mungkin melengkung secara spiral. Daun yang terpuntir seringkali terasa lebih kaku dan kurang lentur dibandingkan dengan daun yang sehat. Ukuran daun yang terkena gejala ini seringkali lebih kecil dari ukuran normal karena pertumbuhannya terganggu. Selain itu, daun yang terpuntir juga sering menunjukkan perubahan warna, seperti menguning, munculnya bercak-bercak, atau warna yang lebih pucat dibandingkan dengan daun sehat. Gejala ini bisa disebabkan oleh berbagai faktor, termasuk defisiensi nutrisi, serangan hama atau penyakit, stres lingkungan, atau ketidakseimbangan hormonal dalam tanaman. Penting untuk mengidentifikasi penyebabnya dan mengambil langkah-langkah perbaikan yang tepat untuk memulihkan kesehatan tanaman cabai.'  
            ],
            [
                'name' => 'Daun melengkung ke bawah',
                'description' => 'Gejala pada tanaman cabai yang mengalami daun melengkung ke bawah adalah tanda yang menunjukkan adanya gangguan pada pertumbuhan dan kesehatan tanaman. Daun yang terpengaruh gejala ini tampak menurun atau bahkan terbalik ke arah tanah, dengan permukaan daun secara keseluruhan cenderung mengarah ke bawah. Tekstur daun yang melengkung ke bawah mungkin terasa lebih lemas dan kurang kaku dibandingkan dengan daun yang sehat, yang biasanya tegang dan lentur. Selain itu, daun yang terpengaruh seringkali memiliki ukuran yang lebih kecil dari ukuran normal karena pertumbuhannya terganggu. Perubahan warna juga mungkin terjadi, seperti menguning, munculnya bercak-bercak, atau warna yang lebih pucat dibandingkan dengan daun sehat. Tanaman cabai yang mengalami gejala ini sering mengalami pertumbuhan yang terhambat secara keseluruhan, yang dapat mengganggu pertumbuhan tunas dan buah serta berpotensi mengurangi hasil panen. Dengan mendeteksi dan mengatasi masalah ini secara tepat, kesehatan dan produktivitas tanaman cabai dapat dipertahankan dengan lebih baik.'  
            ],
            [
                'name' => 'Daun melengkung ke atas',
                'description' => 'Gejala pada tanaman cabai ini adalah tanda yang mengindikasikan adanya gangguan pada pertumbuhan dan kesehatan tanaman. Daun yang terkena gejala ini tampak menaik atau bahkan terbalik ke arah udara, dengan permukaan daun secara keseluruhan cenderung mengarah ke atas, menjauhi tanah. Tekstur daun yang melengkung ke atas mungkin terasa lebih lemas dan kurang kaku dibandingkan dengan daun yang sehat, yang biasanya tegang dan lentur. Selain itu, daun yang terpengaruh seringkali memiliki ukuran yang lebih kecil dari ukuran normal karena pertumbuhannya terganggu. Perubahan warna juga mungkin terjadi, seperti menguning, munculnya bercak-bercak, atau warna yang lebih pucat dibandingkan dengan daun sehat. Tanaman cabai dengan gejala ini sering mengalami pertumbuhan yang terhambat secara keseluruhan, yang dapat mengganggu pertumbuhan tunas dan buah serta berpotensi mengurangi hasil panen. Dengan mendeteksi dan mengatasi masalah ini dengan tepat, kesehatan dan produktivitas tanaman cabai dapat dipertahankan secara lebih baik.'  
            ],
            [
                'name' => 'Buah ada bintik kecil seperti tusukan',
                'description' => 'Gejala pada buah tanaman cabai yang menampilkan bintik-bintik kecil yang menyerupai tusukan atau puncak pada permukaannya adalah tanda adanya gangguan yang mempengaruhi kesehatan buah tersebut. Bintik-bintik kecil tersebut umumnya tersebar secara sporadis di seluruh permukaan buah dan biasanya memiliki ukuran yang kecil. Variasi warna bintik-bintik ini dapat bervariasi, mulai dari coklat tua hingga hitam, tergantung pada tingkat kematangan buah dan jenis patogen atau penyebabnya. Selain itu, tekstur buah juga mungkin terpengaruh, menjadi lebih lembek atau rapuh di sekitar area bintik tersebut. Dengan memperhatikan gejala ini, langkah-langkah pengendalian yang tepat dapat diambil untuk menjaga kesehatan dan kualitas buah tanaman cabai.'  
            ],
            [
                'name' => 'Ditemukan ulat di dalam buah',
                'description' => 'Saat memeriksa buah tanaman cabai, seringkali kita menemukan ulat yang berwarna putih, hijau, atau coklat, tergantung pada jenis hama dan tahap perkembangannya, bersembunyi di dalam buah tersebut. Ulats ini, dengan menggerogoti buah dari dalam, menyebabkan kerusakan serius pada daging buah. Bagian dalam buah mungkin menjadi busuk atau tercemar oleh kotoran ulat. Ukuran ulat yang ditemukan bervariasi, mulai dari yang sangat kecil hingga ukuran yang lebih besar, tergantung pada spesiesnya dan tahap perkembangannya. Dampak dari kehadiran ulat di dalam buah sangat signifikan; selain menurunkan kualitas buah, hal ini juga dapat mengakibatkan kehilangan nilai komersial dan bahkan kerugian yang besar pada hasil panen secara keseluruhan. Oleh karena itu, tindakan pengendalian yang efektif perlu segera diambil untuk mengurangi dampak negatif yang ditimbulkan oleh ulat pada tanaman cabai.'  
            ],
            [
                'name' => 'Daun tersisa jaringan epidermis dan tulang daun saja',
                'description' => 'Gejala pada tanaman cabai yang menampilkan daun dengan hanya tersisa sisa-sisa tipis dari epidermis dan tulang daun, tanpa jaringan daun yang sebenarnya, menggambarkan tingkat kerusakan yang signifikan. Daun yang terkena gejala ini tampak transparan atau hampir tidak memiliki jaringan daun di antara tulang daunnya, sehingga tulang daun menjadi sangat mencolok dan terlihat jelas. Hal ini menunjukkan bahwa sebagian besar jaringan daun, termasuk sel-sel parenkim dan kloroplasnya, telah rusak atau dihilangkan, meninggalkan daun dengan struktur yang hampir seperti kerangka. Tingkat kerusakan yang terlihat pada daun ini mengindikasikan bahwa tanaman cabai telah mengalami serangan atau gangguan yang serius, yang dapat mengganggu pertumbuhan dan kesehatannya secara keseluruhan. Oleh karena itu, pengendalian yang efektif perlu segera diambil untuk meminimalkan dampak negatifnya pada tanaman cabai dan mencegah kerusakan lebih lanjut.'  
            ],
            [
                'name' => 'Buah busuk basah',
                'description' => 'Gejala Gejala pada tanaman cabai ini menggambarkan kondisi di mana buah-buah tersebut mengalami pembusukan yang menyebabkan kelembaban yang berlebihan pada permukaannya. Buah yang terkena gejala ini seringkali tampak lembek dan terlihat basah, dengan sebagian atau seluruh permukaan buah menjadi lembab dan licin. Warna buah yang terkena gejala ini mungkin tampak lebih gelap, atau terdapat perubahan warna menjadi coklat atau hitam pada area yang terkena pembusukan. Tekstur buah yang mengalami pembusukan basah cenderung lunak, bahkan mungkin hancur ketika ditekan. Selain itu, buah yang busuk basah juga seringkali menimbulkan aroma yang tidak sedap atau bau busuk yang cukup kuat. Gejala ini menunjukkan adanya masalah serius yang dapat mengurangi kualitas dan kuantitas hasil panen tanaman cabai, sehingga tindakan pengendalian dan manajemen yang tepat perlu segera diambil untuk mengatasi penyebabnya.'  
            ],
            [
                'name' => 'Buah busuk kering dan di permukaan terdapat bintik coklat kehitaman',
                'description' => 'Gejala pada tanaman cabai yang menunjukkan buah-buah mengalami pembusukan ditandai dengan berbagai ciri. Buah-buah yang terkena gejala ini cenderung tampak mengering dan keriput, dengan tekstur yang kasar dan kering saat disentuh. Permukaan buah yang terinfeksi seringkali ditutupi oleh bintik-bintik coklat kehitaman, yang merupakan tanda adanya pembusukan atau kerusakan pada jaringan buah. Konsistensi buah yang terpengaruh oleh gejala ini juga cenderung lebih keras dan rapuh dibandingkan dengan buah yang sehat. Warna buah yang terkena gejala pembusukan ini mungkin tampak lebih gelap atau berubah menjadi coklat kehitaman, terutama di area yang terinfeksi atau terkena pembusukan. Gejala ini mengindikasikan adanya masalah serius pada tanaman cabai, yang jika tidak segera ditangani dapat mengakibatkan kerugian pada hasil panen dan kesehatan tanaman secara keseluruhan. Oleh karena itu, tindakan pengendalian dan manajemen yang tepat diperlukan untuk mengatasi penyebab gejala ini dan menjaga kesehatan tanaman cabai.'  
            ],
            [
                'name' => 'Layu dari bagian bawah tanaman menjalar ke atas',
                'description' => 'Gejala layu pada tanaman cabai menggambarkan kondisi di mana daun-daun, terutama pada bagian bawah tanaman, mulai menunjukkan tanda-tanda kelelahan dan kekurangan air. Penampilan daun tampak layu, kehilangan kekakuan, dan mungkin mengalami perubahan warna menjadi kekuningan atau kecoklatan. Gejala ini cenderung dimulai dari bagian bawah tanaman dan secara perlahan menjalar ke bagian atas, menyebabkan keseluruhan tanaman terlihat lemah dan tidak sehat. Meskipun tanah di sekitarnya mungkin cukup lembab, tanaman yang terkena gejala ini seringkali menunjukkan tanda-tanda kekurangan air. Penyebab umumnya adalah kerusakan pada sistem perakaran tanaman, yang dapat disebabkan oleh berbagai faktor seperti penyakit, serangan hama, atau kondisi lingkungan yang tidak sesuai. Untuk mencegah lebih lanjutnya gejala layu dan mengembalikan kesehatan tanaman, langkah-langkah perawatan seperti pemantauan rutin, perbaikan drainase tanah, pengendalian hama dan penyakit, serta penyesuaian lingkungan tumbuh dapat diambil.'  
            ],
            [
                'name' => 'Warna batang dan akar kecoklatan',
                'description' => 'Gejala pada tanaman cabai ini menandakan kondisi di mana batang dan akar tanaman menunjukkan perubahan warna menjadi kecoklatan. Batang cabai yang terkena gejala ini mungkin menunjukkan warna coklat yang gelap, terutama di daerah dekat tanah atau di bagian yang terinfeksi atau terluka. Selain itu, akar tanaman juga dapat menunjukkan warna yang sama, menandakan adanya masalah pada sistem perakaran. Perubahan warna ini seringkali merupakan indikasi adanya kerusakan struktural pada tanaman, yang bisa disebabkan oleh penyakit, kelebihan air, kekurangan nutrisi, atau kondisi lingkungan yang tidak sesuai. Penyebab umumnya meliputi infeksi jamur atau bakteri pada akar, kekurangan oksigen karena kelebihan air, atau penyakit vaskular seperti layu bakteri atau fusarium yang menginfeksi jaringan batang dan akar tanaman cabai. Untuk mengatasi gejala ini, diperlukan langkah-langkah pengelolaan tanah yang baik, penggunaan fungisida atau bakterisida yang tepat, serta pemantauan rutin kondisi tanaman untuk mendeteksi gejala awal kerusakan dan mengambil tindakan pencegahan yang diperlukan. Dengan demikian, Anda dapat membantu menjaga kesehatan dan produktivitas tanaman cabai Anda.'  
            ],
            [
                'name' => 'Layu dari bagian atas tanaman, mendadak layu dan permanen',
                'description' => 'Gejala pada tanaman cabai ini mencerminkan kondisi di mana daun-daun pada bagian atas tanaman tiba-tiba menunjukkan tanda-tanda layu yang bersifat permanen. Gejala ini muncul secara tiba-tiba tanpa adanya peringatan sebelumnya, di mana daun-daun yang sebelumnya tampak sehat kehilangan kekakuan dan mulai layu. Perkembangan gejala ini bersifat permanen, yang berarti daun-daun yang terkena tidak akan pulih meskipun diberikan perawatan lebih lanjut. Penyebabnya dapat bervariasi, mulai dari kondisi kekeringan ekstrim, infeksi penyakit layu seperti layu bakteri atau layu fusarium, hingga kerusakan pada sistem perakaran tanaman. Pengendalian dan manajemen yang tepat, seperti pemantauan rutin, irigasi yang tepat, dan pengendalian penyakit dan hama, dapat membantu mencegah dan mengendalikan gejala ini, menjaga kesehatan dan produktivitas tanaman cabai.'  
            ],
            [
                'name' => 'Terdapat bercak bulat berwarna putih/pucat pada daun',
                'description' => 'Gejala pada tanaman cabai ini menandakan adanya perubahan yang mencolok pada permukaan daun. Pada daun tanaman cabai, terlihat adanya bercak bulat yang berwarna putih atau pucat, menonjol dari warna hijau normal daun. Bercak-bercak ini dapat bervariasi dalam ukuran, mulai dari yang sangat kecil hingga yang lebih besar, dan bisa tersebar secara sporadis di seluruh permukaan daun. Warna putih atau pucat pada bercak menonjol dari warna hijau alami daun dan seringkali menjadi ciri khas yang mudah dikenali dari jarak jauh. Meskipun daun mungkin tetap tampak sehat pada area yang tidak terpengaruh, bercak putih atau pucat dapat menyebabkan perubahan tekstur pada daun yang terkena, seperti kekeringan atau kerapuhan. Penyebab umum bercak putih atau pucat ini termasuk infeksi jamur, infeksi bakteri, atau serangan hama seperti kutu daun putih. Pengendalian yang tepat, seperti penggunaan fungisida atau bakterisida, pemantauan rutin, dan pengendalian hama, dapat membantu mencegah dan mengendalikan gejala ini, menjaga kesehatan dan produktivitas tanaman cabai.'  
            ],
            [
                'name' => 'Bercak kecoklatan pada pangkal batang, cabang, atau pucuk tanaman',
                'description' => 'Gejala pada tanaman cabai ini menandakan adanya masalah yang mempengaruhi bagian utama tanaman tersebut. Pada pangkal batang, cabang, atau pucuk tanaman cabai, terlihat adanya bercak kecoklatan yang menonjol dari warna asli tanaman. Bercak-bercak ini bisa memiliki ukuran yang bervariasi, mulai dari yang kecil hingga yang lebih besar, dan mungkin memiliki bentuk yang tidak teratur. Penyebab umum bercak kecoklatan ini dapat berasal dari infeksi penyakit jamur, seperti antraknosa atau busuk pangkal batang, infeksi bakteri seperti bakteriosis, atau kerusakan fisik akibat cedera atau tekanan mekanis. Tindakan pengendalian yang tepat, seperti pemangkasan bagian yang terinfeksi, penggunaan fungisida atau bakterisida, serta perbaikan drainase tanah, dapat membantu mencegah dan mengendalikan penyebaran gejala ini, menjaga kesehatan dan produktivitas tanaman cabai.'  
            ]
        ]);
    }
}
